#include "../Common/Utilities.hlsl"

struct TexelParameters
{
    float waterLevel;
    float sedimentLevel;
};

RWStructuredBuffer<TexelParameters>
    texelParameters;
RWTexture2D<float> resultHeightmap;

struct TexelPipes
{
    float inWaterPipes[3][3];
    float inSedimentPipes[3][3];
};

static const uint2 pipeMap[3][3] =
    {
        {uint2(2, 2), uint2(2, 1), uint2(2, 0)},
        {uint2(1, 2), uint2(1, 1), uint2(1, 0)},
        {uint2(0, 2), uint2(0, 1), uint2(0, 0)},
};
RWStructuredBuffer<TexelPipes> pipesBuffer;

uniform int2 heightmapDimensions; // so as not to GetDimensions() every time
uniform int texelsPerThread;
uniform int iterationIdx;

uniform float rainSolubilityConstant;
uniform float evaporationConstant;
uniform float capacityConstant;
uniform float depositionConstant;
uniform float solubilityConstant;
uniform float maxWaterDepth;

uniform float2 randomSeeds;

uniform float rainNoiseFrequency;

static const float HEIGHT_EPS = 1.0e-3; // texels differing by less are assumed to be at the same level
static const float MIN_WATER = 0.3;

//TODO: add a texture for gradient precompute

#pragma multi_compile GLOBAL_GROUP_8 GLOBAL_GROUP_16 GLOBAL_GROUP_32 GLOBAL_GROUP_64 

// I don't want to perform CPU-side zeroing or change the render target (expensive)
#pragma kernel ResourceInitializer
#if GLOBAL_GROUP_8
[numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
[numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
[numthreads(32, 32, 1)]
#endif
    void ResourceInitializer(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            int2 processedTexel = topLeftCorner + int2(x, y);
            uint processedTexelLin = index2dTo1d(heightmapDimensions, processedTexel);
            texelParameters[processedTexelLin].waterLevel = 0.0;
            texelParameters[processedTexelLin].sedimentLevel = 0.0;
        }
    }
}

#pragma kernel PipePlumber
#if GLOBAL_GROUP_8
    [numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
    [numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
    [numthreads(32, 32, 1)]
#endif
    void PipePlumber(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;
    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 processedTexel = topLeftCorner + uint2(x, y);
            uint lin = index2dTo1d(heightmapDimensions, processedTexel);

            for (int i = 0; i < 3; ++i)
            {
                for (int j = 0; j < 3; ++j)
                {
                    pipesBuffer[lin].inWaterPipes[i][j] = 0;
                    pipesBuffer[lin].inSedimentPipes[i][j] = 0;
                }
            }
        }
    }
}

#pragma kernel RainDropper
#if GLOBAL_GROUP_8
[numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
[numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
[numthreads(32, 32, 1)]
#endif
    void RainDropper(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            int2 processedTexel_i = topLeftCorner + int2(x, y);
            uint2 processedTexel = (uint2)processedTexel_i;
            uint lin = index2dTo1d(heightmapDimensions, processedTexel);

            float currentWaterLevel = texelParameters[lin].waterLevel;
            float currentHeight = resultHeightmap[processedTexel_i];
            float maxAllowedExtraWater = currentHeight / rainSolubilityConstant;

            float extraRainWater = min(maxAllowedExtraWater, pinkNoise2D(((float2)processedTexel + randomSeeds * (float2)heightmapDimensions) * rainNoiseFrequency));
            extraRainWater = extraRainWater < MIN_WATER ? 0.0 : extraRainWater;
            float localSoftness = computeSoftnessCoefficient(computeGradientAtPoint(resultHeightmap, heightmapDimensions, processedTexel), currentHeight, 0.1);
            float heightLoss = extraRainWater * rainSolubilityConstant * localSoftness;

            texelParameters[lin].waterLevel = extraRainWater + currentWaterLevel;     // step 1
            texelParameters[lin].sedimentLevel += min(currentHeight, heightLoss);     // step 2
            resultHeightmap[processedTexel_i] = max(currentHeight - heightLoss, 0.0); // step 2
        }
    }
}

struct WaterDistributionFromTexel
{
    float waterSpreadValue[3][3];
};

// computes how water is distributed from texel
WaterDistributionFromTexel computeWaterDistribution(int2 processedTexel)
{
    WaterDistributionFromTexel nInfo;

    uint centerLin = index2dTo1d(heightmapDimensions, (uint2)processedTexel);
    float waterLevelAtTexel = texelParameters[centerLin].waterLevel;
    float texelHeight = resultHeightmap[processedTexel] + waterLevelAtTexel;

    float sumError = 0.0;
    float sumErrorOut = 0.0;
    float exceedingSum = 0.0;
    int numCriticalNeighbors = 0;

    {
        for (int x = -1; x < 2; ++x)
        {
            for (int y = -1; y < 2; ++y)
            {
                int2 neighborCoord = terrainWrap(processedTexel + int2(x, y), heightmapDimensions);

                uint nLin = index2dTo1d(heightmapDimensions, (uint2)neighborCoord);
                float d = texelHeight - (resultHeightmap[neighborCoord] + texelParameters[nLin].waterLevel);
                if (d > HEIGHT_EPS)
                {
                    numCriticalNeighbors++;
                    exceedingSum = accurateSum(exceedingSum, d, sumErrorOut);
                    sumError += sumErrorOut;
                }
                else
                {
                    d = 0.0;
                }
                nInfo.waterSpreadValue[y + 1][x + 1] = d;
            }
        }
    }
    exceedingSum += sumError;

    if (numCriticalNeighbors == 0)
    {
        [unroll] for (int yy = 0; yy < 3; ++yy)
        {
            [unroll] for (int xx = 0; xx < 3; ++xx)
            {
                nInfo.waterSpreadValue[yy][xx] = 0.0;
            }
        }
        return nInfo;
    }

    // average height of the critical neighbors
    float invCrit = 1.0 / (float)numCriticalNeighbors;
    float averageNeighborHeight = ((float)numCriticalNeighbors * texelHeight - exceedingSum) * invCrit;

    float totalWaterLost = texelHeight - averageNeighborHeight;
    totalWaterLost = max(0.0, totalWaterLost);
    totalWaterLost = min(waterLevelAtTexel, totalWaterLost);

    {
        float invSum = exceedingSum > 0 ? 1.0 / exceedingSum : 0.0;

        for (int x = -1; x < 2; ++x)
        {
            for (int y = -1; y < 2; ++y)
            {
                float d = nInfo.waterSpreadValue[y + 1][x + 1];

                float dWater = totalWaterLost * d * invSum;

                nInfo.waterSpreadValue[y + 1][x + 1] = dWater;
            }
        }
    }

    // how much water the central texel loses
    nInfo.waterSpreadValue[1][1] = -totalWaterLost;
    return nInfo;
}

void applyWaterKernel(int2 processedTexel)
{
    WaterDistributionFromTexel distributionAtTexel = computeWaterDistribution(processedTexel); // step 3

    for (int i = -1; i < 2; ++i)
    {
        for (int j = -1; j < 2; ++j)
        {
            int2 target = terrainWrap(processedTexel + int2(i, j), heightmapDimensions);
            uint lin = index2dTo1d(heightmapDimensions, (uint2)target);

            uint2 targetInPipe = pipeMap[i + 1][j + 1];
            pipesBuffer[lin].inWaterPipes[targetInPipe.x][targetInPipe.y] = distributionAtTexel.waterSpreadValue[j + 1][i + 1];
        }
    }
}

#pragma kernel WaterDistributor
#if GLOBAL_GROUP_8
[numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
[numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
[numthreads(32, 32, 1)]
#endif
    void WaterDistributor(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;
    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 processedTexel = topLeftCorner + uint2(x, y);
            applyWaterKernel(processedTexel);
        }
    }
}

float computeLargerVelocity(int2 processedTexel)
{
    uint centerLin = index2dTo1d(heightmapDimensions, (uint2)processedTexel);

    int neighborTop = index2dTo1d(heightmapDimensions, terrainWrap(processedTexel - int2(0, 1), heightmapDimensions));
    int neighborBottom = index2dTo1d(heightmapDimensions, terrainWrap(processedTexel + int2(0, 1), heightmapDimensions));

    int neighborLeft = index2dTo1d(heightmapDimensions, terrainWrap(processedTexel - int2(1, 0), heightmapDimensions));
    int neighborRight = index2dTo1d(heightmapDimensions, terrainWrap(processedTexel + int2(1, 0), heightmapDimensions));

    float vX = 0.5 * (pipesBuffer[neighborRight].inWaterPipes[1][0] + pipesBuffer[centerLin].inWaterPipes[1][0] - pipesBuffer[neighborLeft].inWaterPipes[1][2] - pipesBuffer[centerLin].inWaterPipes[1][2]);

    float vY = 0.5 * (pipesBuffer[neighborBottom].inWaterPipes[0][1] + pipesBuffer[centerLin].inWaterPipes[0][1] - pipesBuffer[neighborTop].inWaterPipes[2][1] - pipesBuffer[centerLin].inWaterPipes[2][1]);

    float sNormSq = vX * vX + vY * vY;

    int neighborTopLeft = index2dTo1d(heightmapDimensions, terrainWrap(processedTexel - int2(1, 1), heightmapDimensions));
    int neighborBottomRight = index2dTo1d(heightmapDimensions, terrainWrap(processedTexel + int2(1, 1), heightmapDimensions));

    int neighborTopRight = index2dTo1d(heightmapDimensions, terrainWrap(processedTexel + int2(1, -1), heightmapDimensions));
    int neighborBottomLeft = index2dTo1d(heightmapDimensions, terrainWrap(processedTexel + int2(-1, 1), heightmapDimensions));

    // from top left to bottom right
    float vL = 0.5 * (pipesBuffer[neighborBottomRight].inWaterPipes[0][0] + pipesBuffer[centerLin].inWaterPipes[0][0] - pipesBuffer[neighborTopLeft].inWaterPipes[2][2] - pipesBuffer[centerLin].inWaterPipes[2][2]);

    // from bottom left to top right
    float vR = 0.5 * (pipesBuffer[neighborTopRight].inWaterPipes[2][0] + pipesBuffer[centerLin].inWaterPipes[2][0] - pipesBuffer[neighborBottomLeft].inWaterPipes[0][2] - pipesBuffer[centerLin].inWaterPipes[0][2]);

    float dNormSq = vL * vL + vR * vR;

    return sqrt(max(sNormSq, dNormSq));
}

#pragma kernel SedimentDistributor
#if GLOBAL_GROUP_8
[numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
[numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
[numthreads(32, 32, 1)]
#endif
    void SedimentDistributor(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;
    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            int2 processedTexel = topLeftCorner + int2(x, y);
            uint centerLin = index2dTo1d(heightmapDimensions, (uint2)processedTexel);

            float waterLevelAtTexel = texelParameters[centerLin].waterLevel;
            float sedimentLevelAtTexel = texelParameters[centerLin].sedimentLevel;
            float terrainHeightAtTexel = resultHeightmap[processedTexel];

            float sedimentAdjustment = 0.0;

            {
                float2 heightGradientAtTexel = computeGradientAtPoint(resultHeightmap, heightmapDimensions, processedTexel);

                float velocityNorm = computeLargerVelocity(processedTexel);

                float gradientNorm = length(heightGradientAtTexel);
                float sinAlpha = gradientNorm / sqrt(1.0 + gradientNorm * gradientNorm);

                float depthAdjustment = waterLevelAtTexel >= maxWaterDepth ? 1.0 : (1.0 - (maxWaterDepth - waterLevelAtTexel) / maxWaterDepth);
                float localSedimentCapacity = capacityConstant * max(sinAlpha, 0.2) * velocityNorm * depthAdjustment;

                if (sedimentLevelAtTexel <= localSedimentCapacity)
                {
                    // sediment amount is increased
                    float localSoftness = computeSoftnessCoefficient(heightGradientAtTexel, terrainHeightAtTexel, 0.1);
                    // we can't dissolve more than height
                    sedimentAdjustment = min(localSoftness * (localSedimentCapacity - sedimentLevelAtTexel) * solubilityConstant, terrainHeightAtTexel);
                }
                else
                {
                    // sediment amount is reduced
                    sedimentAdjustment = -(sedimentLevelAtTexel - localSedimentCapacity) * depositionConstant;
                }
                // resultHeightmap[processedTexel] = gradientNorm;
            }

            float waterLostAtTexel = abs(pipesBuffer[centerLin].inWaterPipes[1][1]);
            float intermediateSedimentLevel = sedimentLevelAtTexel + sedimentAdjustment;

            for (int i = -1; i < 2; ++i)
            {
                for (int j = -1; j < 2; ++j)
                {
                    int2 processedNeighbor = terrainWrap(processedTexel + int2(i, j), heightmapDimensions);
                    int nLin = index2dTo1d(heightmapDimensions, processedNeighbor);

                    uint2 targetInPipe = pipeMap[i + 1][j + 1];

                    float waterReceived = pipesBuffer[nLin].inWaterPipes[targetInPipe.x][targetInPipe.y];
                    float sedimentReceived = intermediateSedimentLevel * (waterReceived / waterLevelAtTexel);

                    pipesBuffer[nLin].inSedimentPipes[targetInPipe.x][targetInPipe.y] = sedimentReceived;
                }
            }

            // this change will be taken into account during evaporation stage
            pipesBuffer[centerLin].inSedimentPipes[1][1] = /*due depth*/ sedimentAdjustment - /*due water flow*/ (intermediateSedimentLevel * (waterLostAtTexel / waterLevelAtTexel));
            resultHeightmap[processedTexel] = max(0.0, terrainHeightAtTexel - sedimentAdjustment);
        }
    }
}

#pragma kernel WaterEvaporator
#if GLOBAL_GROUP_8
    [numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
    [numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
    [numthreads(32, 32, 1)]
#endif
    void WaterEvaporator(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    float evap = saturate(evaporationConstant);

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            int2 processedTexel_i = topLeftCorner + int2(x, y);
            uint2 processedTexel = (uint2)processedTexel_i;

            uint lin = index2dTo1d(heightmapDimensions, processedTexel);

            float extraPipeWater = 0.0;
            float extraPipeSediment = 0.0;
            for (int i = 0; i < 3; ++i)
            {
                for (int j = 0; j < 3; ++j)
                {
                    extraPipeWater += pipesBuffer[lin].inWaterPipes[i][j];
                    extraPipeSediment += pipesBuffer[lin].inSedimentPipes[i][j];
                }
            }
            float waterLevelAtTexel = max(0.0, texelParameters[lin].waterLevel + extraPipeWater);
            float sedimentLevelAtTexel = max(0.0, texelParameters[lin].sedimentLevel + extraPipeSediment);

            float newWaterLevel = waterLevelAtTexel * (1.0 - evap);

            texelParameters[lin].waterLevel = newWaterLevel;
            texelParameters[lin].sedimentLevel = sedimentLevelAtTexel;
        }
    }
}

// evaporates whatever water is left after the erosion process
#pragma kernel FinalWaterEvaporator
#if GLOBAL_GROUP_8
[numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
[numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
[numthreads(32, 32, 1)]
#endif
    void FinalWaterEvaporator(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    float evap = saturate(evaporationConstant);

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            int2 processedTexel_i = topLeftCorner + int2(x, y);
            uint2 processedTexel = (uint2)processedTexel_i;

            uint lin = index2dTo1d(heightmapDimensions, processedTexel);
            float extraPipeSediment = 0.0;
            for (int i = 0; i < 3; ++i)
            {
                for (int j = 0; j < 3; ++j)
                {
                    extraPipeSediment += pipesBuffer[lin].inSedimentPipes[i][j];
                }
            }

            float sedimentLevelAtTexel = max(0.0, texelParameters[lin].sedimentLevel + extraPipeSediment);
            resultHeightmap[processedTexel_i] += sedimentLevelAtTexel;
        }
    }
}
