#include "../Common/Utilities.hlsl"

RWStructuredBuffer<float> waterLevel;
RWTexture2D<float> resultHeightmap;

uniform int2 heightmapDimensions; // so as not to GetDimensions() every time
uniform int texelsPerThread;
uniform float solubilityConstant;
uniform float evaporationConstant;

uniform float2 noiseDisplacement;

uniform uint permuteA;

static const float EPS = 1.0e-6;

#pragma kernel RainDropper
[numthreads(32, 32, 1)] void RainDropper(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            int2 processedTexel_i = topLeftCorner + int2(x, y);
            uint2 processedTexel = (uint2)processedTexel_i;
            uint lin = index2dTo1d(heightmapDimensions, processedTexel);

            float extraRainWater = pinkNoise2D((float2)processedTexel + noiseDisplacement * (float2)heightmapDimensions);

            waterLevel[lin] += extraRainWater;                                        // step 1
            resultHeightmap[processedTexel_i] -= extraRainWater * solubilityConstant; // step 2
        }
    }
}

struct WaterDistributionFromTexel
{
    float waterSpreadValue[3][3];
};

// computes how water (and implicit sediment) is distributed from texel
WaterDistributionFromTexel computeWaterDistribution(int2 processedTexel)
{
    WaterDistributionFromTexel nInfo;

    uint centerLin = index2dTo1d(heightmapDimensions, (uint2)processedTexel);
    float waterLevelAtTexel = waterLevel[centerLin];
    float texelHeight = resultHeightmap[processedTexel] + waterLevelAtTexel;

    float exceedingSum = EPS;
    int numCriticalNeighbors = 0;

    {
        for (int x = -1; x < 2; ++x)
        {
            for (int y = -1; y < 2; ++y)
            {
                int2 neighborCoord = terrainWrap(processedTexel + int2(x, y), heightmapDimensions);

                uint nLin = index2dTo1d(heightmapDimensions, (uint2)neighborCoord);
                float neighborWater = waterLevel[nLin];

                float d = texelHeight - (resultHeightmap[neighborCoord] + neighborWater);
                if (d > 0.0)
                {
                    numCriticalNeighbors++;
                }
                else
                {
                    d = 0.0;
                }

                exceedingSum += d;
                nInfo.waterSpreadValue[y + 1][x + 1] = d;
            }
        }
    }

    if (numCriticalNeighbors == 0)
    {
        [unroll] for (int yy = 0; yy < 3; ++yy)
        {
            [unroll] for (int xx = 0; xx < 3; ++xx)
            {
                nInfo.waterSpreadValue[yy][xx] = 0.0;
            }
        }
        return nInfo;
    }

    // average height of the critical neighbors
    float invCrit = 1.0 / (float)numCriticalNeighbors;
    float averageNeighborHeight = ((float)numCriticalNeighbors * texelHeight - exceedingSum) * invCrit;

    float totalWaterLost = texelHeight - averageNeighborHeight;
    totalWaterLost = max(0.0, totalWaterLost);
    totalWaterLost = min(waterLevelAtTexel, totalWaterLost);

    {
        float invSum = 1.0 / max(exceedingSum, EPS);

        for (int x = -1; x < 2; ++x)
        {
            for (int y = -1; y < 2; ++y)
            {
                float d = nInfo.waterSpreadValue[y + 1][x + 1];
                nInfo.waterSpreadValue[y + 1][x + 1] = totalWaterLost * d * invSum;
            }
        }
    }

    // how much water the central texel loses
    nInfo.waterSpreadValue[1][1] = -totalWaterLost;
    return nInfo;
}

void applyKernel(int2 processedTexel)
{
    WaterDistributionFromTexel distributionAtTexel = computeWaterDistribution(processedTexel); // step 3

    for (int i = -1; i < 2; ++i)
    {
        for (int j = -1; j < 2; ++j)
        {
            int2 target = terrainWrap(processedTexel + int2(i, j), heightmapDimensions);
            uint lin = index2dTo1d(heightmapDimensions, (uint2)target);
            waterLevel[lin] += distributionAtTexel.waterSpreadValue[j + 1][i + 1];
        }
    }
}

#pragma kernel HydraulicCoreEroder
[numthreads(32, 32, 1)] void HydraulicCoreEroder(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    int innerSide = texelsPerThread - 2;
    int totalTexelsPerThread = innerSide * innerSide;

    uint N = (uint)totalTexelsPerThread;
    uint permuteB = (uint)((globalId.x + globalId.y + groupId.x + groupId.y) % N);

    // iterates over the grid in a permuted order
    for (uint idx = 0; idx < N; ++idx)
    {
        uint permutedIdx = (permuteA * idx + permuteB) % N;

        int x = (int)(permutedIdx / (uint)innerSide);
        int y = (int)(permutedIdx % (uint)innerSide);

        int2 processedTexel = topLeftCorner + int2(x, y) + int2(2, 2);

        applyKernel(processedTexel);

        AllMemoryBarrier();
    }
}

#pragma kernel HydraulicBorderEroder
    [numthreads(32, 32, 1)] void HydraulicBorderEroder(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    int stepMultiplier = 1 - (texelsPerThread % 2);

    { // horizontal strip
        int totalTexelsPerThreadHorizontal = texelsPerThread * 2;

        uint N = (uint)totalTexelsPerThreadHorizontal;
        uint permuteBHorizontal = (uint)((globalId.x + globalId.y + groupId.x + groupId.y) % N);

        for (uint idx = 0; idx < N; ++idx)
        {
            uint permutedIdx = (permuteA * idx + permuteBHorizontal) % N;

            int x = (int)(permutedIdx % (uint)texelsPerThread);
            int y = ((int)permutedIdx + (permutedIdx / texelsPerThread) * stepMultiplier) % 2;

            int2 processedTexel = topLeftCorner + int2(x, y);

            applyKernel(processedTexel);
            AllMemoryBarrier();
        }
    }

    { // vertical strip
        int truncatedTexelsPerThread = texelsPerThread - 2;
        int totalTexelsPerThreadVertical = truncatedTexelsPerThread * 2;

        uint N = (uint)totalTexelsPerThreadVertical;
        uint permuteBVertical = (uint)((globalId.x + globalId.y + groupId.x + groupId.y) % N);

        for (uint idx = 0; idx < N; ++idx)
        {
            uint permutedIdx = (permuteA * idx + permuteBVertical) % N;

            int y = (int)(permutedIdx % (uint)truncatedTexelsPerThread);
            int x = (permutedIdx + (permutedIdx / truncatedTexelsPerThread) * stepMultiplier) % 2;

            int2 processedTexel = topLeftCorner + int2(x, y) + int2(0, 2);

            applyKernel(processedTexel);
            AllMemoryBarrier();
        }
    }
}

#pragma kernel WaterEvaporator
[numthreads(32, 32, 1)] void WaterEvaporator(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    float evap = saturate(evaporationConstant);

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            int2 processedTexel_i = topLeftCorner + int2(x, y);
            uint2 processedTexel = (uint2)processedTexel_i;

            uint lin = index2dTo1d(heightmapDimensions, processedTexel);
            float waterLevelAtTexel = waterLevel[lin];

            float newWaterLevel = waterLevelAtTexel * (1.0 - evap);

            float removedWater = waterLevelAtTexel - newWaterLevel;
            float sedimentationValue = removedWater * solubilityConstant;

            // step 4
            waterLevel[lin] = newWaterLevel;
            resultHeightmap[processedTexel_i] += sedimentationValue;
        }
    }
}
