#include "../Common/Utilities.hlsl"

struct ErosionParticle
{
    float2 pos;
    float2 dir;
    float2 vel;
    float w;
    float s;
};

RWTexture2D<float> resultHeightmap;
RWStructuredBuffer<ErosionParticle> particlesBuffer;
uniform uint2 heightmapDimensions;
uniform uint particlesPerThread;

uniform float inertia;
uniform float capacity;
uniform float minSlope;
uniform float deposition;
uniform float erosion;
uniform float gravity;
uniform float evaporation;
uniform int erosionNeighborhood; // for 3x3 grid that would be 1, for 5x5 - 2
uniform float erosionDistanceSumPrecompute;

bool checkParticleIsValid(ErosionParticle particle)
{
    // TODO: check steps
    float2 particlePos = particle.pos;
    return (particlePos.x >= 0 && particlePos.y >= 0) && (particlePos.x < heightmapDimensions.x && particlePos.y < heightmapDimensions.y) && particle.w > 0.0;
}

float sampleHeightmapBilinear(float2 coord)
{
    int2 basePart = int2(floor(coord));
    float2 fracPart = frac(coord);

    float v00 = resultHeightmap[basePart];
    float v10 = resultHeightmap[terrainWrap(heightmapDimensions, basePart + int2(1, 0))];
    float v01 = resultHeightmap[terrainWrap(heightmapDimensions, basePart + int2(0, 1))];
    float v11 = resultHeightmap[terrainWrap(heightmapDimensions, basePart + int2(1, 1))];

    float v0 = lerp(v00, v10, fracPart.x);
    float v1 = lerp(v01, v11, fracPart.x);

    return lerp(v0, v1, fracPart.y);
}

float removeSediment(int2 erosionCenter, float targetAmountToRemove)
{
    float actualSedimentRemoved = 0.0;
    for (int x = -erosionNeighborhood; x <= erosionNeighborhood; ++x)
    {
        for (int y = -erosionNeighborhood; y <= erosionNeighborhood; ++y)
        {
            // TODO: multiply with hardness coefficient
            float weight = (erosionNeighborhood - sqrt(x * x + y * y)) / erosionDistanceSumPrecompute;
            uint2 affectedNeighborCoefficient = terrainWrap(heightmapDimensions, erosionCenter + int2(x, y));

            float currentTexeleHeight = resultHeightmap[affectedNeighborCoefficient];
            float localAmountRemoved = min(currentTexeleHeight, weight * targetAmountToRemove);
            actualSedimentRemoved += localAmountRemoved;
            resultHeightmap[affectedNeighborCoefficient] = max(0.0, currentTexeleHeight - localAmountRemoved);
        }
    }

    return actualSedimentRemoved;
}

void depositSediment(int2 erosionCenter, float amountToDeposit)
{
    float uniformWeight = rcp(5.0);
    for (int x = -1; x <= 1; ++x)
    {
        for (int y = -1; y <= 1; ++y)
        {
            uint2 affectedNeighborCoefficient = erosionCenter + int2(x, y);
            resultHeightmap[affectedNeighborCoefficient] += !(x == y) * uniformWeight * amountToDeposit;
        }
    }
}

float2 computeUniformRandomCoordinates(uint2 targetCoordinates, int nonce)
{
    uint seed = seedFromXYPass(targetCoordinates.x, targetCoordinates.y, nonce);
    float u1 = u01FromUint(pcgHash(seed));
    float u2 = u01FromUint(pcgHash(seed ^ 0x68BC21EBu));

    return float2(max(u1, EPS), max(u2, EPS));
}

// TODO: add a kernel that would eliminate dead particles and spawn new ones in their place (particles that are either out of bounds, out of water or out of steps)
// TODO: figure out how I can improve numerical stability and reduce chances of races. This is the case when I may want to introduce change map (or just plain copy the heightmap)

#pragma kernel ParticlesInitializer
[numthreads(64, 1, 1)] void ParticlesInitializer(uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupThreadID)
{
    uint threadRangeStart = globalId.x * particlesPerThread;
    for (uint idx = 0; idx < particlesPerThread; ++idx)
    {
        uint processedParticleIdx = threadRangeStart + idx;
        float2 uniformCoefficients = computeUniformRandomCoordinates(uint2(globalId.x, processedParticleIdx), groupId.x);
        float dropSize = sampleGaussBoxMuller(uniformCoefficients);

        particlesBuffer[processedParticleIdx].pos = uniformCoefficients * (float2)heightmapDimensions;
        particlesBuffer[processedParticleIdx].dir = float2(0.0, 0.0);
        particlesBuffer[processedParticleIdx].vel = float2(0.0, 0.0);
        particlesBuffer[processedParticleIdx].w = dropSize;
        particlesBuffer[processedParticleIdx].s = 0.0;
    }
}

#pragma kernel Integrator
    [numthreads(64, 1, 1)] void Integrator(uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupThreadID)
{
    uint threadRangeStart = globalId.x * particlesPerThread;
    for (uint idx = 0; idx < particlesPerThread; ++idx)
    {
        uint processedParticleIdx = threadRangeStart + idx;

        if (!checkParticleIsValid(particlesBuffer[processedParticleIdx]))
            continue;

        float2 oldParticlePosition = particlesBuffer[processedParticleIdx].pos;
        float2 oldParticleVelocity = particlesBuffer[processedParticleIdx].vel;
        float oldSedimentValue = particlesBuffer[processedParticleIdx].s;

        uint2 floorOldParticlePosition = floor(oldParticlePosition);
        float2 interpolationCoefficients = frac(oldParticlePosition);

        float2 currentGradient = float2((resultHeightmap[terrainWrap(heightmapDimensions, floorOldParticlePosition + uint2(1, 0))] - resultHeightmap[floorOldParticlePosition]) * (1 - interpolationCoefficients.x) + (resultHeightmap[terrainWrap(heightmapDimensions, floorOldParticlePosition + uint2(1, 1))] - resultHeightmap[terrainWrap(heightmapDimensions, floorOldParticlePosition + uint2(0, 1))]) * interpolationCoefficients.x, (resultHeightmap[terrainWrap(heightmapDimensions, floorOldParticlePosition + uint2(0, 1))] - resultHeightmap[floorOldParticlePosition]) * (1 - interpolationCoefficients.y) + (resultHeightmap[terrainWrap(heightmapDimensions, floorOldParticlePosition + uint2(1, 1))] - resultHeightmap[terrainWrap(heightmapDimensions, floorOldParticlePosition + uint2(1, 0))]) * interpolationCoefficients.y);

        float2 newParticleDirection = normalize(particlesBuffer[processedParticleIdx].dir * inertia - currentGradient * (1.0 - inertia));
        float2 newParticlePosition = oldParticlePosition + newParticleDirection;

        float oldHeight = sampleHeightmapBilinear(oldParticlePosition);
        float newHeight = sampleHeightmapBilinear(newParticlePosition);
        float heightDelta = newHeight - oldHeight;

        float sedimentValueUpdate = 0.0;
        if (heightDelta >= 0.0)
        {
            // TODO: drop some sediment for we have moved upwards
            float amountToDeposit = oldSedimentValue;
            depositSediment(floorOldParticlePosition, amountToDeposit);
            sedimentValueUpdate = -oldSedimentValue;
        }
        else
        {
            float newCapacity = max(-heightDelta, minSlope) * oldParticleVelocity * particlesBuffer[processedParticleIdx].w * capacity;
            if (oldSedimentValue > newCapacity)
            {
                // TODO: drop sediment at old pos
                float amountToDeposit = (oldSedimentValue - newCapacity) * deposition;
                depositSediment(floorOldParticlePosition, amountToDeposit);
                sedimentValueUpdate = -amountToDeposit;
            }
            else
            {
                // TODO: take sediment from old pos
                float amountToRemove = min((newCapacity - oldSedimentValue) * erosion, -heightDelta);
                float actualSedimentRemoved = removeSediment(floorOldParticlePosition, amountToRemove);
                sedimentValueUpdate = actualSedimentRemoved;
            }
        }

        float2 newParticleVelocity = sqrt(oldParticleVelocity * oldParticleVelocity + heightDelta * gravity);
        float newW = particlesBuffer[processedParticleIdx].w * (1 - evaporation);

        // TODO: actually update all parameters of the particle
        particlesBuffer[processedParticleIdx].pos = newParticlePosition;
        particlesBuffer[processedParticleIdx].dir = newParticleDirection;
        particlesBuffer[processedParticleIdx].vel = newParticleVelocity;
        particlesBuffer[processedParticleIdx].w = newW;
        particlesBuffer[processedParticleIdx].s = max(particlesBuffer[processedParticleIdx].s + sedimentValueUpdate, 0.0);
    }
}