#include "../Common/Utilities.hlsl"

RWTexture2D<float> resultHeightmap;
uniform int2 heightmapDimensions; // so as not to GetDimensions() every time

uniform int texelsPerThread;
uniform float distributionCoefficient; // this parameter now controls how "sturdy" the material constituting the terrain is
uniform float talusThreshold;
uniform float2 noiseDisplacement;

uniform uint permuteA;

static const float BIG_FLOAT = 3.402823466e+38f;

// diagonal texels are further away from the kernel center, and so we assume they receive less material than direct neighbors
static const float heightDistributionDistanceCoefficients[3][3] =
    {
        {0.85, 1.0, 0.85},
        {1.0, 0.0, 1.0},
        {0.85, 1.0, 0.85}};

struct TexelHeightDistribution
{
    float heightSpreadValue[3][3];
};

float computeSingleHeightIncrement(float heightDistance, float distanceSum, float totalHeightRemoved)
{
    return totalHeightRemoved * (heightDistance / distanceSum);
}

// determines how material is distirbuted around a texel due to thermal erosion
TexelHeightDistribution computeHeightDistribution(int2 processedTexel)
{
    TexelHeightDistribution nInfo;

    float texelHeight = resultHeightmap[processedTexel];

    float exceedingSum = 1.0e-5;
    float maxHeightDistance = 0.0;
    int numCriticalNeighbors = 0;
    float minHeightDistance = BIG_FLOAT;

    for (int x = -1; x < 2; ++x)
    {
        for (int y = -1; y < 2; ++y)
        {
            int2 ncoord = terrainWrap(processedTexel + int2(x, y), heightmapDimensions);
            float d = texelHeight - resultHeightmap[ncoord];

            if (d > talusThreshold)
            {
                maxHeightDistance = max(maxHeightDistance, d);
                minHeightDistance = min(minHeightDistance, d);
                numCriticalNeighbors++;
            }
            else
            {
                d = 0.0;
            }

            exceedingSum += d;
            nInfo.heightSpreadValue[y + 1][x + 1] = d;
        }
    }

    float avalancheRatio = 0.0;
    if (numCriticalNeighbors > 0 && maxHeightDistance > 1.0e-8)
    {
        // the smaller the distance betweem the lowest and highest neighbors -> the more prominent "avalanche"
        avalancheRatio = 1.0 - (maxHeightDistance - minHeightDistance) / maxHeightDistance;
    }

    uint seed = seedFromXYPass(processedTexel.x, processedTexel.y, numCriticalNeighbors);
    float u1 = u01FromUint(pcgHash(seed));

    // zero-mean gaussian is shifted to the estimated ratio. u2 is kept at zero to ensure sigma=1
    float dynamicDistributionCoefficient = clamp((sampleGaussBoxMuller(float2(u1, 0.0)) + avalancheRatio), 1.0e-2, 1.0) * distributionCoefficient;

    float totalHeightRemoved = (numCriticalNeighbors > 0) ? (dynamicDistributionCoefficient * (maxHeightDistance - talusThreshold)) : 0.0;

    // to make sure the central texel does not end up higher than its closest neighbor
    float heightConsistencyThreshold = (minHeightDistance * exceedingSum) / (minHeightDistance + exceedingSum + 1.0e-5);
    totalHeightRemoved = (totalHeightRemoved <= heightConsistencyThreshold) ? totalHeightRemoved : heightConsistencyThreshold;

    for (int x = -1; x < 2; ++x)
    {
        for (int y = -1; y < 2; ++y)
        {
            float d = nInfo.heightSpreadValue[y + 1][x + 1];
            nInfo.heightSpreadValue[y + 1][x + 1] = heightDistributionDistanceCoefficients[y + 1][x + 1] * computeSingleHeightIncrement(d, exceedingSum, totalHeightRemoved);
        }
    }

    // how much height the central texel loses
    nInfo.heightSpreadValue[1][1] = -totalHeightRemoved;

    return nInfo;
}

void applyKernel(int2 processedTexel)
{
    TexelHeightDistribution distributionAtTexel = computeHeightDistribution(processedTexel);

    for (int i = -1; i < 2; ++i)
    {
        for (int j = -1; j < 2; ++j)
        {
            int2 p = terrainWrap(processedTexel + int2(i, j), heightmapDimensions);
            resultHeightmap[p] += distributionAtTexel.heightSpreadValue[j + 1][i + 1];
        }
    }
}

// race-free update of quadrants' centers
#pragma kernel ThermalCoreEroder
[numthreads(32, 32, 1)] void ThermalCoreEroder(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    int innerSide = texelsPerThread - 2;
    int totalTexelsPerThread = innerSide * innerSide;

    uint N = (uint)totalTexelsPerThread;
    uint permuteB = (uint)((globalId.x + globalId.y + groupId.x + groupId.y) % N);

    // iterates over the grid in a permuted order
    for (uint idx = 0; idx < N; ++idx)
    {
        uint permutedIdx = (permuteA * idx + permuteB) % N;

        int x = (int)(permutedIdx / (uint)innerSide);
        int y = (int)(permutedIdx % (uint)innerSide);

        int2 processedTexel = topLeftCorner + int2(x, y) + int2(2, 2);

        applyKernel(processedTexel);

        AllMemoryBarrier();
    }
}

// race-free update of quadrants' borders
#pragma kernel ThermalBorderEroder
    [numthreads(32, 32, 1)] void ThermalBorderEroder(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    int2 topLeftCorner = (int2)globalId.xy * texelsPerThread;

    int stepMultiplier = 1 - (texelsPerThread % 2);

    { // horizontal strip
        int totalTexelsPerThreadHorizontal = texelsPerThread * 2;

        uint N = (uint)totalTexelsPerThreadHorizontal;
        uint permuteBHorizontal = (uint)((globalId.x + globalId.y + groupId.x + groupId.y) % N);

        for (uint idx = 0; idx < N; ++idx)
        {
            uint permutedIdx = (permuteA * idx + permuteBHorizontal) % N;

            int x = (int)(permutedIdx % (uint)texelsPerThread);
            int y = ((int)permutedIdx + (permutedIdx / texelsPerThread) * stepMultiplier) % 2;
            int2 processedTexel = topLeftCorner + int2(x, y);

            applyKernel(processedTexel);
            AllMemoryBarrier();
        }
    }

    { // vertical strip
        int truncatedTexelsPerThread = texelsPerThread - 2;
        int totalTexelsPerThreadVertical = truncatedTexelsPerThread * 2;

        uint N = (uint)totalTexelsPerThreadVertical;
        uint permuteBVertical = (uint)((globalId.x + globalId.y + groupId.x + groupId.y) % N);

        for (uint idx = 0; idx < N; ++idx)
        {
            uint permutedIdx = (permuteA * idx + permuteBVertical) % N;

            int y = (int)(permutedIdx % (uint)truncatedTexelsPerThread);
            int x = (permutedIdx + (permutedIdx / truncatedTexelsPerThread) * stepMultiplier) % 2;

            int2 processedTexel = topLeftCorner + int2(x, y) + int2(0, 2);

            applyKernel(processedTexel);
            AllMemoryBarrier();
        }
    }
}
