#include "../Common/Utilities.hlsl"

RWTexture2D<float> resultHeightmap;
uniform int2 heightmapDimensions; // so as not to GetDimensions() every time

uniform int texelsPerThread;
uniform float distributionCoefficient; // this parameter now controls how "sturdy" the material constituting the terrain is
uniform float talusThreshold;
uniform float2 noiseDisplacement;

static const float MAX_FLOAT = 0xFFFFFFF;

static const float heightDistributionDistanceCoefficients[3][3] =
    {
        {0.85, 1.0, 0.85},
        {1.0, 0.0, 1.0},
        {0.85, 1.0, 0.85}};

// TODO: get rid of (mitigate) lattice artifacts. The order of thread execution is decisive, and so this goal is tightly coupled with the optimization taks above.

struct TexelHeightDistribution
{
    float heightSpreadValue[3][3];
};

float computeSingleHeightIncrement(float heightDistance, float distanceSum, float totalHeightRemoved)
{
    return totalHeightRemoved * (heightDistance / distanceSum);
}

TexelHeightDistribution computeHeightDistribution(int2 processedTexel)
{
    TexelHeightDistribution nInfo;

    float texelHeight = resultHeightmap[processedTexel];

    float exceedingSum = 1.0e-5;
    float maxHeightDistance = 0.0;
    int numCriticalNeighbors = 0;
    float minHeightDistance = MAX_FLOAT;
    for (int x = -1; x < 2; ++x)
    {
        for (int y = -1; y < 2; ++y)
        {
            float d = texelHeight - resultHeightmap[terrainWrap(processedTexel + int2(x, y), heightmapDimensions)];
            if (d > talusThreshold)
            {
                maxHeightDistance = max(maxHeightDistance, d);
                minHeightDistance = min(minHeightDistance, d);
                numCriticalNeighbors++;
            }
            else
            {
                d = 0.0;
            }

            exceedingSum += d;
            nInfo.heightSpreadValue[y + 1][x + 1] = d;
        }
    }

    // the smaller the distance betweem the lowest and highest neighbors -> the more prominent is the effect of "avalanche" -> the higher is the distribution coefficient (i.e. the fraction of the height difference distributed)
    float avalancheRatio = 1.0 - (maxHeightDistance - minHeightDistance) / maxHeightDistance;
    uint seed = seedFromXYPass(processedTexel.x, processedTexel.y, numCriticalNeighbors);
    float u1 = u01FromUint(pcgHash(seed));
    // zero-mean gaussian is shifted to the estimated ratio. u2 is kept at zero to ensure sigma=1
    float dynamicDistributionCoefficient = clamp((sampleGaussBoxMuller(float2(u1, 0.0)) + avalancheRatio), 1.0e-2, 1.0) * distributionCoefficient;

    float totalHeightRemoved = numCriticalNeighbors > 0 ? dynamicDistributionCoefficient * (maxHeightDistance - talusThreshold) : 0.0;
    float heightConsistencyThreshold = (minHeightDistance * exceedingSum) / (minHeightDistance + exceedingSum + 1.0e-5);
    // to make sure the central texel does not end up higher than its closest neighbor
    totalHeightRemoved = totalHeightRemoved <= heightConsistencyThreshold ? totalHeightRemoved : heightConsistencyThreshold;

    for (int x = -1; x < 2; ++x)
    {
        for (int y = -1; y < 2; ++y)
        {
            float d = nInfo.heightSpreadValue[y + 1][x + 1];
            nInfo.heightSpreadValue[y + 1][x + 1] = heightDistributionDistanceCoefficients[y + 1][x + 1] * computeSingleHeightIncrement(d, exceedingSum, totalHeightRemoved);
        }
    }

    // how much height the central texel loses
    nInfo.heightSpreadValue[1][1] = -totalHeightRemoved;

    return nInfo;
}

void applyKernel(uint2 processedTexel)
{
    TexelHeightDistribution distributionAtTexel = computeHeightDistribution(processedTexel);

    for (int i = -1; i < 2; ++i)
    {
        for (int j = -1; j < 2; ++j)
        {
            resultHeightmap[terrainWrap(processedTexel + int2(i, j), heightmapDimensions)] += distributionAtTexel.heightSpreadValue[j + 1][i + 1];
        }
    }
}

#pragma kernel ThermalCoreEroder
[numthreads(32, 32, 1)] void ThermalCoreEroder(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    int2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 2; x < texelsPerThread; ++x)
    {
        for (int y = 2 + (x % 2); y < texelsPerThread; y += 2)
        {
            uint2 processedTexel = topLeftCorner + uint2(x, y);
            applyKernel(processedTexel);
            AllMemoryBarrier(); //so that a thread can read back what it has just written
        }
    }

    for (int x = 2; x < texelsPerThread; ++x)
    {
        for (int y = 3 - (x % 2); y < texelsPerThread; y += 2)
        {
            uint2 processedTexel = topLeftCorner + uint2(x, y);
            applyKernel(processedTexel);
            AllMemoryBarrier(); //so that a thread can read back what it has just written
        }
    }
}

#pragma kernel ThermalBorderEroder
    [numthreads(32, 32, 1)] void ThermalBorderEroder(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    // horizontal strip
    for (uint x_h = 0; x_h < texelsPerThread; ++x_h)
    {
        uint y_h = (x_h % 2);
        uint2 processedTexel = topLeftCorner + uint2(x_h, y_h);
        applyKernel(processedTexel);
        AllMemoryBarrier(); //so that a thread can read back what it has just written
    }

    for (uint x_h = 0; x_h < texelsPerThread; ++x_h)
    {
        uint y_h = 1 - (x_h % 2);
        uint2 processedTexel = topLeftCorner + uint2(x_h, y_h);
        applyKernel(processedTexel);
        AllMemoryBarrier(); //so that a thread can read back what it has just written
    }

    // vertical strip
    for (uint y_v = 2; y_v < texelsPerThread; ++y_v)
    {
        uint x_v = (y_v % 2);
        uint2 processedTexel = topLeftCorner + uint2(x_v, y_v);
        applyKernel(processedTexel);
        AllMemoryBarrier(); //so that a thread can read back what it has just written
    }

    for (uint y_v = 2; y_v < texelsPerThread; ++y_v)
    {
        uint x_v = 1 - (y_v % 2);
        uint2 processedTexel = topLeftCorner + uint2(x_v, y_v);
        applyKernel(processedTexel);
        AllMemoryBarrier(); //so that a thread can read back what it has just written
    }
}
