#include "../../3rdparty/hlsl_noise/ashima/noise2D.hlsl"
#include "../../3rdparty/hlsl_noise/ashima/cellular2D.hlsl"
#include "../../3rdparty/hlsl_noise/common/stegu-math.hlsl"
#include "./Common/Utilities.hlsl"

#pragma multi_compile_local GROUP_1 GROUP_2 GROUP_4 GROUP_8 GROUP_16 GROUP_32 GROUP_64

RWTexture2D<float> Result;

uniform int threadDomainTexelWidth;
uniform int texelWidthDivided;
uniform uint texelWidthDivisionFactor; // 1,2,4,8...
uniform uint texelWidthDivisionIteration; //1,2,3...
uniform uint2 targetDimensions;        // so as not to GetDimensions() every time

uniform uint threadSubdomainsX;
uniform uint threadSubdomainsY;

uniform float octaveAmplitude;
uniform float noiseFrequency;
uniform int2 noiseDisplacement;
uniform float worleyFrequency;
// uniform float perlinFrequency;

// TODO: can I employ gradients of noise here?

float sampleGaussianNoise(float2 noiseTextureIdx)
{
    return sampleGaussBoxMuller(noiseTextureIdx);
}

float sampleNoise(float2 noiseTextureIdx)
{
    // return snoise(sampleGaussianNoise(noiseTextureIdx) * perlinFrequency); // domain warping
    return sampleGaussBoxMuller(noiseTextureIdx);
}

float sampleWorleyNoise(float2 noiseTextureIdx)
{
#define RANGE_THRSH_CEIL 0.6
#define RANGE_THRSH_FLOOR 0.35
// EFFECTIVE_RANGE = RANGE_THRSH_CEIL - RANGE_THRSH_FLOOR
#define EFFECTIVE_RANGE 0.25
#define EPSILON 3.0e-2
#define RIDGE_FALLOF_SPEED 0.5

    float2 f1_f2 = cellular(noiseTextureIdx);

    if (abs(f1_f2.x - f1_f2.y) >= EPSILON)
    {
        return f1_f2.x;
    }

    if (f1_f2.x >= RANGE_THRSH_CEIL)
    {
        return f1_f2.x;
    }
    return (max(f1_f2.x - RANGE_THRSH_FLOOR, 0.0) * RIDGE_FALLOF_SPEED) / EFFECTIVE_RANGE;
}

// these end up normalized and uniformly distributed
float2 computeNoiseCoordinates(uint2 targetTextureCoordinates)
{
    uint seed = seedFromXYPass(targetTextureCoordinates.x, targetTextureCoordinates.y, texelWidthDivided);
    float u1 = u01FromUint(pcgHash(seed));
    float u2 = u01FromUint(pcgHash(seed ^ 0x68BC21EBu));
    return float2(u1, u2);
}

#pragma kernel IntializeTexture
#if GROUP_1
[numthreads(1, 1, 1)]
#elif GROUP_2
[numthreads(2, 2, 1)]
#elif GROUP_4
[numthreads(4, 4, 1)]
#if GROUP_8
[numthreads(8, 8, 1)]
#elif GROUP_16
[numthreads(16, 16, 1)]
#elif GROUP_32
[numthreads(32, 32, 1)]
#if GROUP_64
[numthreads(64, 64, 1)]
#endif
    void IntializeTexture(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    uint2 topLeftCellIdx = globalId.xy * threadDomainTexelWidth;

    float2 worleyCoordinates = (topLeftCellIdx / (float2)targetDimensions) * worleyFrequency + noiseDisplacement;
    Result[topLeftCellIdx.xy] = sampleWorleyNoise(worleyCoordinates) * octaveAmplitude;
}

#pragma kernel AddExtraNoise
    [numthreads(16, 16, 1)] void AddExtraNoise(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    uint2 topLeftCellIdx = globalId.xy * threadDomainTexelWidth;

    for (int x = 0; x < threadDomainTexelWidth; ++x)
    {
        for (int y = 0; y < threadDomainTexelWidth; ++y)
        {
            uint2 targetIdx = topLeftCellIdx + uint2(x, y);
            Result[targetIdx] = Result[targetIdx] + sampleGaussianNoise(computeNoiseCoordinates(targetIdx)) * octaveAmplitude;
        }
    }
}

#pragma kernel Transition12
#if GROUP_1
[numthreads(1, 1, 1)]
#elif GROUP_2
[numthreads(2, 2, 1)]
#elif GROUP_4
[numthreads(4, 4, 1)]
#if GROUP_8
[numthreads(8, 8, 1)]
#elif GROUP_16
[numthreads(16, 16, 1)]
#elif GROUP_32
[numthreads(32, 32, 1)]
#if GROUP_64
[numthreads(64, 64, 1)]
#endif
    void Transition12(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    uint2 topLeftCellIdx = globalId.xy * threadDomainTexelWidth;

    for (int x = 0; x < texelWidthDivisionFactor; ++x)
    {
        for (int y = 0; y < texelWidthDivisionFactor; ++y)
        {
            int2 subdivisionIdx = topLeftCellIdx.xy + uint2(texelWidthDivided + 2 * texelWidthDivided * x, texelWidthDivided + 2 * texelWidthDivided * y);

            // let the terrain wrap around currently
            float averageNeighbors =
                (Result[terrainWrap(subdivisionIdx + int2(texelWidthDivided, texelWidthDivided), targetDimensions)] +
                 Result[terrainWrap(subdivisionIdx + int2(texelWidthDivided, -texelWidthDivided), targetDimensions)] +
                 Result[terrainWrap(subdivisionIdx + int2(-texelWidthDivided, texelWidthDivided), targetDimensions)] +
                 Result[terrainWrap(subdivisionIdx + int2(-texelWidthDivided, -texelWidthDivided), targetDimensions)]) /
                4.0;

            Result[subdivisionIdx] = averageNeighbors + sampleNoise(computeNoiseCoordinates(subdivisionIdx)) * octaveAmplitude;
        }
    }
}

#pragma kernel Transition21
#if GROUP_1
[numthreads(1, 1, 1)]
#elif GROUP_2
[numthreads(2, 2, 1)]
#elif GROUP_4
[numthreads(4, 4, 1)]
#if GROUP_8
[numthreads(8, 8, 1)]
#elif GROUP_16
[numthreads(16, 16, 1)]
#elif GROUP_32
[numthreads(32, 32, 1)]
#if GROUP_64
[numthreads(64, 64, 1)]
#endif
    void Transition21(uint3 localID : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID, uint3 groupId : SV_GroupID)
{
    uint2 topLeftCellIdx = globalId.xy * threadDomainTexelWidth;

    int numYPasses = pow(2, texelWidthDivisionIteration);
    int numXPasses = texelWidthDivisionFactor;

    for (uint y = 0; y < numYPasses; ++y)
    {
        int xShiftAmount = (1 - (y % 2)) * texelWidthDivided;
        for (uint x = 0; x < numXPasses; ++x)
        {
            int2 diamondIdx = topLeftCellIdx.xy + uint2(x * 2 * texelWidthDivided + xShiftAmount, y * texelWidthDivided);

            float neighborLeft = 0.0;
            float neighborRight = 0.0;
            float neighborTop = 0.0;
            float neighborBottom = 0.0;

            int numberValid = 0;

            if (diamondIdx.x != 0)
            {
                neighborLeft = Result[terrainWrap(diamondIdx + int2(-texelWidthDivided, 0), targetDimensions)];
                numberValid++;
            }

            if (diamondIdx.x != targetDimensions.x - 1)
            {
                neighborRight = Result[terrainWrap(diamondIdx + int2(+texelWidthDivided, 0), targetDimensions)];
                numberValid++;
            }

            if (diamondIdx.y != 0)
            {
                neighborTop = Result[terrainWrap(diamondIdx + int2(0, -texelWidthDivided), targetDimensions)];
                numberValid++;
            }

            if (diamondIdx.y != targetDimensions.y - 1)
            {
                neighborBottom = Result[terrainWrap(diamondIdx + int2(0, +texelWidthDivided), targetDimensions)];
                numberValid++;
            }

            Result[diamondIdx] = ((neighborLeft +
                                   neighborRight +
                                   neighborTop +
                                   neighborBottom) /
                                  numberValid) +
                                 sampleNoise(computeNoiseCoordinates(diamondIdx)) * octaveAmplitude;
        }
    }
}
