#include "../../3rdparty/hlsl_noise/ashima/psrdnoise2D.hlsl"
#include "../../3rdparty/hlsl_noise/ashima/noise2D.hlsl"

RWTexture2D<float> inputTexture;    // white-black, unsigned normalized
RWTexture2D<float> outputTexture; // red channel, signed unnormalized

RWStructuredBuffer<uint2> buffer1;
RWStructuredBuffer<uint2> buffer2;

uniform int currentSourceBuffer;
uniform int floodStepSize;

uniform int texelsPerThread;
uniform int bufferSideLength;

static const uint MAX_UINT = 0xFFFFFFFFu;
static const uint2 MAX_COORD = uint2(MAX_UINT, MAX_UINT);
static const float shoreDistanceThreshold = 20.0;
static const float shoreBaseHeight = 1.0;

uint tabularToLinearIdx(uint2 tabularIdx)
{
    return tabularIdx.x + (uint)bufferSideLength * tabularIdx.y;
}

uint2 readFromBuffer(uint2 targetCoord)
{
    if (currentSourceBuffer == 0)
    {
        return buffer1[tabularToLinearIdx(targetCoord)];
    }
    else
    {
        return buffer2[tabularToLinearIdx(targetCoord)];
    }
}

void writeToBuffer(uint2 targetCoord, uint2 newValue)
{
    if (currentSourceBuffer == 0)
    {
        buffer2[tabularToLinearIdx(targetCoord)] = newValue;
    }
    else
    {
        buffer1[tabularToLinearIdx(targetCoord)] = newValue;
    }
}

bool texelIsWhiteForMask(float texelColor)
{
    // return abs(1.0 - texelColor) <= 1.0e-3;
    return texelColor > 0.2;
}

// fractal accumulation of simplx noise
float fbm(float2 uv, float startFreq)
{
    float freq = startFreq;
    float amp = 1.0;
    float n = 0.0;
    for (int i = 0; i < 5; i++)
    {
        n += amp * snoise(uv * freq);
        freq *= 2.0;
        amp *= 0.5;
    }

    return n;
}

float coastlineComputer(float2 texelCoord)
{
    float2 uv = texelCoord / bufferSideLength;
    float basePerlinFreq = 2.0;

    float freq = basePerlinFreq / 1.5;
    float amp = 1.0;
    float n = 0.0;
    float2 gsum = float2(5.0, 5.0);

    float disp = 0.0;
    for (int i = 0; i < 5; i++)
    {
        float3 psrdSample = amp * srdnoise(uv * freq + gsum * 0.15, 0.5 * freq);
        ;
        disp += psrdSample.x;
        gsum += psrdSample.yz * amp;

        freq *= 2.0;
        amp *= 0.5;
    }
    disp = 0.55 + disp * 0.35;

    float2 q = float2(fbm(uv + float2(0.0, 0.7), basePerlinFreq),
                      fbm(uv + float2(0.7, 0.0), basePerlinFreq));
    n = fbm(uv + 0.05 * q, basePerlinFreq) - disp;

    float smokeEffect = 0.5 + n * 0.35;

    return smokeEffect;
}

//TODO: handle proper writeback to normalized texture
#pragma kernel CoastlineGenerator
[numthreads(16, 16, 1)] void CoastlineGenerator(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 texelCoord = topLeftCorner + uint2(x, y);
            inputTexture[texelCoord] = coastlineComputer(texelCoord);
        }
    }
}

// TODO: using kernel stride of 2 gives 4 times fewer reads but 2 times more writes at border pixels. Can it be optimized?
#pragma kernel MaskToSeedBuffer
    [numthreads(16, 16, 1)] void MaskToSeedBuffer(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 kernelCenter = topLeftCorner + uint2(x, y);
            float texelColor = inputTexture[kernelCenter];

            if (texelIsWhiteForMask(texelColor))
            {
                // center is white
                bool blackFound = false;
                for (int i = -1; i < 2 && !blackFound; ++i)
                {
                    for (int j = -1; j < 2 && !blackFound; ++j)
                    {
                        uint2 targetNeighbor = uint2(clamp((int)kernelCenter.x + i, 0, bufferSideLength - 1), clamp((int)kernelCenter.y + j, 0, bufferSideLength - 1));
                        float neighborColor = inputTexture[targetNeighbor];
                        if (!texelIsWhiteForMask(neighborColor))
                        {
                            buffer1[tabularToLinearIdx(kernelCenter)] = kernelCenter;
                            blackFound = true;
                        }
                    }
                }

                if (!blackFound)
                {
                    buffer1[tabularToLinearIdx(kernelCenter)] = MAX_COORD;
                }
            }
            else
            {
                // center is black
                buffer1[tabularToLinearIdx(kernelCenter)] = MAX_COORD;
            }
        }
    }
}

#pragma kernel FloodingStep
[numthreads(16, 16, 1)] void FloodingStep(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 cellCoords = topLeftCorner + uint2(x, y);

            uint minSquareDistance = MAX_UINT;
            uint2 closestSeed = MAX_COORD;

            for (int i = -1; i < 2; ++i)
            {
                int targetX = (int)cellCoords.x + i * floodStepSize;

                if (targetX < 0 || targetX >= bufferSideLength)
                {
                    continue;
                }

                for (int j = -1; j < 2; ++j)
                {
                    int targetY = (int)cellCoords.y + j * floodStepSize;

                    if (targetY < 0 || targetY >= bufferSideLength)
                    {
                        continue;
                    }

                    uint2 targetCoord = uint2(targetX, targetY);
                    uint2 closestSeedAtTarget = readFromBuffer(targetCoord);

                    if (closestSeedAtTarget.x == MAX_UINT && closestSeedAtTarget.y == MAX_UINT)
                    {
                        continue;
                    }

                    uint2 closestSeedDistanceVector = closestSeedAtTarget - cellCoords;
                    uint squareDistance = dot(closestSeedDistanceVector, closestSeedDistanceVector);
                    if (squareDistance < minSquareDistance)
                    {
                        minSquareDistance = squareDistance;
                        closestSeed = closestSeedAtTarget;
                    }
                }
            }

            writeToBuffer(cellCoords, closestSeed);
        }
    }
}

//TODO: first normalize the buffer -> then combine it with the input 
#pragma kernel SeedBufferToHieghtmap
[numthreads(16, 16, 1)] void SeedBufferToHieghtmap(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 cellCoords = topLeftCorner + uint2(x, y);

            float texelColor = inputTexture[cellCoords];

            uint2 seedCoordinates = readFromBuffer(cellCoords);
            float actualDistance = length((int2)seedCoordinates - (int2)cellCoords);

            float extraHeight = 0;
            if (texelIsWhiteForMask(texelColor))
            {
                // outputTexture[cellCoords] = actualDistance < shoreBaseHeight ? shoreBaseHeight : actualDistance;
                extraHeight = actualDistance < shoreBaseHeight ? shoreBaseHeight : actualDistance;
            }
            else
            {
                // outputTexture[cellCoords] = actualDistance <= shoreDistanceThreshold ? shoreBaseHeight : 0.0;
                extraHeight = actualDistance <= shoreDistanceThreshold ? shoreBaseHeight : 0.0;
            }

            outputTexture[cellCoords] = texelColor + extraHeight;
        }
    }
}

// TODO: kernel for high-frequency post-processing