#include "./Common/Utilities.hlsl"
#include "../../3rdparty/hlsl_noise/ashima/psrdnoise2D.hlsl"
#include "../../3rdparty/hlsl_noise/ashima/noise2D.hlsl"

RWStructuredBuffer<float> inputTexture; // white-black, unsigned normalized
RWTexture2D<float> outputTexture;       // red channel, signed unnormalized

RWStructuredBuffer<uint2> floodingBuffer1;
RWStructuredBuffer<uint2> floodingBuffer2;

uniform int currentSourceBuffer;
uniform int floodStepSize;

uniform int texelsPerThread;
uniform int bufferSideLength;
uniform float shoreBaseHeight;
uniform float simplexFrequency;
uniform int maskBorderWidth;
uniform float shoreDistanceThreshold;
uniform float randomFloats;
uniform float flowPerturbationStrength;
uniform float basePerturbationStrength;

static const uint MAX_UINT = 0xFFFFFFFFu;
static const uint2 MAX_COORD = uint2(MAX_UINT, MAX_UINT);

#pragma multi_compile GLOBAL_GROUP_8 GLOBAL_GROUP_16 GLOBAL_GROUP_32 GLOBAL_GROUP_64
#pragma multi_compile USE_MASK NOT_USE_MASK

uint2 readFromBuffer(uint2 targetCoord)
{
    if (currentSourceBuffer == 0)
    {
        return floodingBuffer1[index2dTo1d(uint2(bufferSideLength, bufferSideLength), targetCoord)];
    }
    else
    {
        return floodingBuffer2[index2dTo1d(uint2(bufferSideLength, bufferSideLength), targetCoord)];
    }
}

void writeToBuffer(uint2 targetCoord, uint2 newValue)
{
    if (currentSourceBuffer == 0)
    {
        floodingBuffer2[index2dTo1d(uint2(bufferSideLength, bufferSideLength), targetCoord)] = newValue;
    }
    else
    {
        floodingBuffer1[index2dTo1d(uint2(bufferSideLength, bufferSideLength), targetCoord)] = newValue;
    }
}

// tells if a texel is considered part of the mask
bool texelIsWhiteForMask(float texelColor)
{
    // return sqrt(texelColor) > 0.7;
    return texelColor > 0.49;
}

// tells if texel is considered part of land when 'punching' lakes
bool texelIsWhiteForLake(float texelColor)
{
    return texelColor > 0.03;
}

// fractal accumulation of simplx noise
float fbm(float2 uv, float startFreq)
{
    float freq = startFreq;
    float amp = 1.0;
    float n = 0.0;
    for (int i = 0; i < 5; i++)
    {
        n += amp * snoise(uv * freq);
        freq *= 2.0;
        amp *= 0.5;
    }

    return n;
}

float3 computeClosestPointOnEllipse(float a, float b, float2 pointOfInterest)
{
    float scaling = (a * b) / sqrt(pointOfInterest.x * pointOfInterest.x * b * b + pointOfInterest.y * pointOfInterest.y * a * a);
    float2 actualEllipsePoint = pointOfInterest * scaling;

    return float3(actualEllipsePoint, scaling);
}

float maskCoefficient(float2 texelPosition)
{
    float halfLength = bufferSideLength / 2.0;
    float innerA = halfLength - maskBorderWidth;
    float innerB = halfLength - maskBorderWidth;

    float outerA = halfLength;
    float outerB = halfLength;

    float3 closestInner = computeClosestPointOnEllipse(innerA, innerB, texelPosition);
    float3 closestOuter = computeClosestPointOnEllipse(outerA, outerB, texelPosition);

    float falloffLength = length(closestOuter.xy - closestInner.xy);
    float distanceToInner = length(texelPosition - closestInner.xy);

    return 1.0 - clamp((distanceToInner / falloffLength) * (float)(closestInner.z < 1.0), 0.0, 1.0);
}

float computeFlowNoise(float2 uv, float startFreq)
{
    float amp = 0.9;
    float2 gsum = float2(0.2, 0.2);

    float disp = 0.0;
    for (int i = 0; i < 5; i++)
    {
        float3 psrdSample = amp * srdnoise(uv * startFreq + gsum * flowPerturbationStrength, 0.5 * startFreq);
        disp += psrdSample.x;
        gsum += psrdSample.yz * amp;

        startFreq *= 2.0;
        amp *= 0.5;
    }

    return disp;
}

float coastlineComputer(float2 texelCoord)
{
    float2 uv = randomFloats + (texelCoord / bufferSideLength);

    float addFlow = 1.0 - (0.85 + computeFlowNoise(uv, simplexFrequency / 1.3));
    float subFlow = 1.0 - (0.75 + computeFlowNoise(uv, simplexFrequency / 1.7));

#if USE_MASK
    float maskValue = maskCoefficient(texelCoord - float2(bufferSideLength / 2.0, bufferSideLength / 2.0));
#elif NOT_USE_MASK
    float maskValue = 1.0;
#endif
    float2 q = float2(fbm(uv + float2(0.0, 0.7), simplexFrequency),
                      fbm(uv + float2(0.7, 0.0), simplexFrequency));
    float n = maskValue * fbm(uv + basePerturbationStrength * q, simplexFrequency) + addFlow - subFlow;

    float smoke = 0.5 * maskValue + n * 0.25;
    return clamp(smoke, 0.0, 1.0);
}

#pragma kernel CoastlineGenerator
#if GLOBAL_GROUP_8
[numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
[numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
[numthreads(32, 32, 1)]
#endif
    void CoastlineGenerator(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 texelCoord = topLeftCorner + uint2(x, y);
            inputTexture[index2dTo1d(uint2(bufferSideLength, bufferSideLength), texelCoord)] = coastlineComputer(texelCoord);
            // outputTexture[texelCoord]  = coastlineComputer(texelCoord);
        }
    }
}

// TODO: using kernel stride of 2 gives 4 times fewer reads but 2 times more writes at border pixels. Can it be optimized?
#pragma kernel MaskToSeedBuffer
#if GLOBAL_GROUP_8
    [numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
    [numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
    [numthreads(32, 32, 1)]
#endif
    void MaskToSeedBuffer(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 kernelCenter = topLeftCorner + uint2(x, y);
            uint kernelCenterLin = index2dTo1d(uint2(bufferSideLength, bufferSideLength), kernelCenter);

            if (texelIsWhiteForMask(inputTexture[kernelCenterLin]))
            {
                // center is white
                bool blackFound = false;
                for (int i = -1; i < 2 && !blackFound; ++i)
                {
                    for (int j = -1; j < 2 && !blackFound; ++j)
                    {
                        uint2 targetNeighbor = uint2(clamp((int)kernelCenter.x + i, 0, bufferSideLength - 1), clamp((int)kernelCenter.y + j, 0, bufferSideLength - 1));
                        float neighborColor = inputTexture[index2dTo1d(uint2(bufferSideLength, bufferSideLength), targetNeighbor)];
                        if (!texelIsWhiteForMask(neighborColor))
                        {
                            floodingBuffer1[kernelCenterLin] = kernelCenter;
                            blackFound = true;
                        }
                    }
                }

                if (!blackFound)
                {
                    floodingBuffer1[kernelCenterLin] = MAX_COORD;
                }
            }
            else
            {
                // center is black
                floodingBuffer1[kernelCenterLin] = MAX_COORD;
            }
        }
    }
}

#pragma kernel FloodingStep
#if GLOBAL_GROUP_8
[numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
[numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
[numthreads(32, 32, 1)]
#endif
    void FloodingStep(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 cellCoords = topLeftCorner + uint2(x, y);

            uint minSquareDistance = MAX_UINT;
            uint2 closestSeed = MAX_COORD;

            for (int i = -1; i < 2; ++i)
            {
                int targetX = (int)cellCoords.x + i * floodStepSize;

                if (targetX < 0 || targetX >= bufferSideLength)
                {
                    continue;
                }

                for (int j = -1; j < 2; ++j)
                {
                    int targetY = (int)cellCoords.y + j * floodStepSize;

                    if (targetY < 0 || targetY >= bufferSideLength)
                    {
                        continue;
                    }

                    uint2 closestSeedAtTarget = readFromBuffer(uint2(targetX, targetY));

                    if (closestSeedAtTarget.x == MAX_UINT && closestSeedAtTarget.y == MAX_UINT)
                    {
                        continue;
                    }

                    uint2 closestSeedDistanceVector = closestSeedAtTarget - cellCoords;
                    uint squareDistance = dot(closestSeedDistanceVector, closestSeedDistanceVector);
                    if (squareDistance < minSquareDistance)
                    {
                        minSquareDistance = squareDistance;
                        closestSeed = closestSeedAtTarget;
                    }
                }
            }

            writeToBuffer(cellCoords, closestSeed);
        }
    }
}

#pragma kernel SeedBufferToHieghtmap
#if GLOBAL_GROUP_8
    [numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
    [numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
    [numthreads(32, 32, 1)]
#endif
    void SeedBufferToHieghtmap(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 cellCoords = topLeftCorner + uint2(x, y);

            uint2 seedCoordinates = readFromBuffer(cellCoords);
            float actualDistance = length((int2)seedCoordinates - (int2)cellCoords);

            if (texelIsWhiteForMask(inputTexture[index2dTo1d(uint2(bufferSideLength, bufferSideLength), cellCoords)]))
            {
                outputTexture[cellCoords] = (actualDistance + shoreBaseHeight);
            }
            else
            {
                outputTexture[cellCoords] = lerp(shoreBaseHeight, 0.0, min(actualDistance, shoreDistanceThreshold) / shoreDistanceThreshold);
            }
        }
    }
}

#pragma kernel SDFPostprocessor
#if GLOBAL_GROUP_8
[numthreads(8, 8, 1)]
#elif GLOBAL_GROUP_16
[numthreads(16, 16, 1)]
#elif GLOBAL_GROUP_32
[numthreads(32, 32, 1)]
#endif
    void SDFPostprocessor(uint3 localId : SV_GroupThreadID, uint3 globalId : SV_DispatchThreadID)
{
    uint2 topLeftCorner = globalId.xy * texelsPerThread;

    for (int x = 0; x < texelsPerThread; ++x)
    {
        for (int y = 0; y < texelsPerThread; ++y)
        {
            uint2 cellCoords = topLeftCorner + uint2(x, y);

            float inputTexelColor = inputTexture[index2dTo1d(uint2(bufferSideLength, bufferSideLength), cellCoords)];
            float distanceAtTexel = outputTexture[cellCoords];

            //"lake" formation
            inputTexelColor *= (float)(texelIsWhiteForLake(inputTexelColor));

            // clamp goes here since we expect more 'noisy' features to appear where tectonic processes were the most porminent - at mountains
            outputTexture[cellCoords] = distanceAtTexel + inputTexelColor * clamp(distanceAtTexel, 0.45, 1.0);
        }
    }
}