#include "../../3rdparty/hlsl_noise/ashima/psrdnoise2D.hlsl"

#pragma kernel UberNoiseTerrainGenerator

uniform int groupScaleFactor;
uniform float noiseFrequency;

uniform float sharpness;
uniform float slopeErosion;
uniform float perturbationStrength;
uniform int numOctaves;

// GLSL	                    HLSL
// gl_GlobalInvocationID	SV_DispatchThreadID
// gl_LocalInvocationID	    SV_GroupThreadID
// gl_WorkGroupID	        SV_GroupID
// gl_NumWorkGroups	        passed manually / constant buffer

// uvec3	gl_NumWorkGroups	    number of work groups that have been dispatched set by glDispatchCompute()
// uvec3	gl_WorkGroupSize	    size of the work group (local size) operated on defined with layout
// uvec3	gl_WorkGroupID	        index of the work group currently being operated on
// uvec3	gl_LocalInvocationID	index of the current work item in the work group
// uvec3	gl_GlobalInvocationID	global index of the current work item (gl_WorkGroupID * gl_WorkGroupSize + gl_LocalInvocationID)
// uint	    gl_LocalInvocationIndex	1d index representation of gl_LocalInvocationID (gl_LocalInvocationID.z * gl_WorkGroupSize.x * gl_WorkGroupSize.y + gl_LocalInvocationID.y * gl_WorkGroupSize.x + gl_LocalInvocationID.x)

// TODO: when possible, I should use analytical derivatives of the resulting terrain

RWTexture2D<float> Result;
const float2x2 m = float2x2(0.8, -0.6, 0.6, 0.8);

#define PI 3.141592654

[numthreads(32, 32, 1)] void UberNoiseTerrainGenerator(uint3 id : SV_GroupThreadID)
{
    for (int i = 0; i < groupScaleFactor; ++i)
    {
        for (int j = 0; j < groupScaleFactor; ++j)
        {
            int2 actualTextureIdx = id.xy * groupScaleFactor + int2(i, j);
            float2 floatIdx = (float2)actualTextureIdx;

            float2 slopeErosionDerivativeSum = clamp(sdnoise(floatIdx).x, -0.15, 0.15).xx;
            float2 perturbDerivativeSum = float2(0.0, 0.0);
            float noiseResult = 0.0;
            float lfSum = 0;

            float octaveAmplitude = 1.0;
            float octaveFrequency = noiseFrequency;
            float2 samplePosition = float2(0.0, 0.0);

            for (int o = 0; o < numOctaves; ++o)
            {
                samplePosition = (floatIdx * octaveFrequency) + perturbDerivativeSum;

                float3 startNoiseValue = sdnoise(samplePosition);
                float featureNoise = startNoiseValue.x;
                float2 featureDerivative = startNoiseValue.yz;

                float ridgedNoise = 1.0 - abs(featureNoise);
                float billowNoise = ridgedNoise * ridgedNoise;
                featureNoise = lerp(featureNoise, billowNoise, max(0.0, sharpness));
                featureNoise = lerp(featureNoise, ridgedNoise, abs(min(0.0, sharpness)));
                // featureNoise *= exp(-dot(featureDerivative, featureDerivative)) * sharpness;

                // TODO: rework to use amplitude damping technique. Generally, define the usage of amplitude(s).
                // TODO: add feature amplification 

                slopeErosionDerivativeSum += featureDerivative * slopeErosion;
                perturbDerivativeSum += featureDerivative * perturbationStrength;
                float derivativeNorm = dot(slopeErosionDerivativeSum, slopeErosionDerivativeSum);
                noiseResult += octaveAmplitude  * featureNoise * (1.0 / (1.0 + derivativeNorm));

                octaveAmplitude /= 2.0;
                octaveFrequency *= 2.0;
            }

            Result[actualTextureIdx] = (noiseResult + 1.0) / 2.0;
        }
    }
}
